### ISSUE TITLE
AcceptNegotiator.php string handling

### ISSUE THREAD

**Issue by cfuerst** [chubbyphp/chubbyphp-negotiation#2]
chubbyphp-negotiation/src/AcceptNegotiator.php:98 has an unsafe explode which can throw notices if the accept header string does not contain any slash

**Comment by dominikzogg** [comment]
@cfuerst https://github.com/chubbyphp/chubbyphp-negotiation/releases/tag/1.2.1

**Comment by cfuerst** [comment]
thnx!
