### ISSUE TITLE
AcceptLanguageNegotiator can result in a PHP NOTICE because of undefined offset

### ISSUE THREAD

**Issue by haeber** [chubbyphp/chubbyphp-negotiation#4]
When we have a Accept-Language like "de" Chubbyphp\Negotiation\AcceptLanguageNegotator will throw a PHP NOTICE on line 61
- Undefined offset: 1

```
[$attributeKey, $attributeValue] = explode('=', $attribute);
```
Reason is that it is possible, that there is no equal sign "=" in the header value.

See https://github.com/chubbyphp/chubbyphp-negotiation/blob/master/src/AcceptLanguageNegotiator.php#L61

Thanks in Advance.

**Comment by dominikzogg** [comment]
@haeber please provide a concrete example

**Comment by haeber** [comment]
We have a some calls to our apis which have an invalid Accept-Language header like
```
accept-language: de;
```

See the trailing semicolon without an qvalue.

This goes directly through the AcceptLanguageNegotiator and results in the mentioned PHP Notice. Officially this is invalid, see https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4, but it is sent to us. I suggest to close this issue again. Maybe the AcceptLanguageNegotiator could validate the value before it tries to extract it contents, but maybe this is not worth it.

**Comment by haeber** [comment]
Thanks very much. :thumbsup:

**Comment by dominikzogg** [comment]
you're welcome, thanks for preparation
