### ISSUE TITLE
BC in the NegotiatorInterface

### ISSUE THREAD

**Issue by marko-ilic** [chubbyphp/chubbyphp-negotiation#8]
In the version 1.8.1 BC was introduced with changing the return type of the method _negotiate_

```
-    public function negotiate(Request $request);
+    public function negotiate(Request $request): ?NegotiatedValueInterface;
```

**Comment by dominikzogg** [comment]
It was already documented like this, means the implementation could return this value since the beginning.
Annoying yes (wouldn't do it again, had much code to update), BC no

**Comment by healerz** [comment]
It's not about the returned value, this is fine. But changing an interface to be more strict is a BC, since whoever implements the interface has to be at least as strict, so imo this is a BC.

**Comment by dominikzogg** [comment]
Its as strict as the phpdoc always was, by definition this us not a BC (soft and hard typing are treated the same).

**Comment by healerz** [comment]
Ah sorry, wasn't aware of this, all good then. Even though I agree, I would have changed such a thing in a major version.

**Comment by dominikzogg** [comment]
@healerz me too, but i don't see a reason to revert it after it happens

**Comment by healerz** [comment]
No sorry, but that makes it still a BC, that's like you expect people that implement this interface to upfront implement it with actual strict return types. Because if they don't their implementation will break

**Comment by dominikzogg** [comment]
php-cs-fixer setup is a bit abrasive, and I have overlooked it

**Comment by healerz** [comment]
All good now, more as a general discussion about what makes a BC a BC 😄

**Comment by marko-ilic** [comment]
We can close this issue. @dominikzogg thanks for the explanation.
